### ISSUE TITLE
course form failure

### ISSUE THREAD

**Issue by leticiaseixas** [w3c/wai-course-list#193] opened 2022-06-15 13:49 UTC
[Video of problem](https://mit.zoom.us/rec/play/UsY4k8lPu_oNE1Xg02lG-_BnSxMZyAxXxGtUHTnThLdFh8bhgfnrdJTr4IsnjmAdY92apRSlBVNdrmDj.0QFy7Hg9i-qUOw2L?continueMode=true&_x_zm_rtaid=rUOGXJEgTX-EHg63pmcmfg.1655300987936.2df84edb53a3ec64668c8e47d7598641&_x_zm_rhtaid=353)

Best guess characters are breaking form to JSON  conversion

**Comment by SteveALee** [comment] 2022-06-15 15:09
Here's the Netlify function logs - they are only kept for 7 days so archiving now!

```
Jun 9, 01:03:51 PM: 82415588 INFO   Processing form wai-course-list/submission 3a485600-e7ec-11ec-b26c-7faa457c0cf3
Jun 9, 01:03:51 PM: 82415588 Duration: 160.14 ms	Memory Usage: 59 MB	Init Duration: 212.19 ms	
Jun 9, 01:04:01 PM: f3825233 INFO   Processing form wai-course-list/submission 400facf0-e7ec-11ec-b26c-7faa457c0cf3
Jun 9, 01:04:01 PM: f3825233 Duration: 151.99 ms	Memory Usage: 60 MB	
Jun 9, 03:25:10 PM: 14efb9cb INFO   Processing form wai-course-list/submission f8602510-e7ff-11ec-b5c8-d1bc43643989
Jun 9, 03:25:10 PM: 14efb9cb ERROR  GitHub returned failure: 422, {"message":"Invalid request.\n\nFor 'links/0/schema', \"submission_date\" is not an object.","documentation_url":"https://docs.github.com/rest/reference/repos#create-a-repository-dispatch-event"}
Jun 9, 03:25:11 PM: 14efb9cb Duration: 142.19 ms	Memory Usage: 60 MB	Init Duration: 199.40 ms	
Jun 9, 03:31:56 PM: 6ca297ff INFO   Processing form wai-course-list/submission ea82fde0-e800-11ec-b405-c189c8ec1787
Jun 9, 03:31:57 PM: 6ca297ff Duration: 163.16 ms	Memory Usage: 59 MB	Init Duration: 213.90 ms	
Jun 9, 03:41:50 PM: cc037b35 INFO   Processing form wai-course-list/submission 4c147330-e802-11ec-a03c-e93eeec0ecab
Jun 9, 03:41:50 PM: cc037b35 ERROR  GitHub returned failure: 422, {"message":"Invalid request.\n\nFor 'links/0/schema', \"submission_date\" is not an object.","documentation_url":"https://docs.github.com/rest/reference/repos#create-a-repository-dispatch-event"}
Jun 9, 03:41:50 PM: cc037b35 Duration: 133.86 ms	Memory Usage: 59 MB	Init Duration: 165.34 ms	
Jun 9, 03:52:50 PM: 9e22a38c INFO   Processing form wai-course-list/submission d58c2440-e803-11ec-a058-75d273434049
Jun 9, 03:52:50 PM: 9e22a38c Duration: 143.05 ms	Memory Usage: 59 MB	Init Duration: 182.29 ms	
Jun 9, 03:54:36 PM: 642659cd INFO   Processing form wai-course-list/submission 149cdb20-e804-11ec-a058-75d273434049
Jun 9, 03:54:36 PM: 642659cd Duration: 159.29 ms	Memory Usage: 60 MB	
Jun 9, 04:02:59 PM: d09f8c44 INFO   Processing form wai-course-list/submission 405908a0-e805-11ec-a149-6984d0c76acf
Jun 9, 04:02:59 PM: d09f8c44 Duration: 156.42 ms	Memory Usage: 59 MB	Init Duration: 184.03 ms	
Jun 9, 04:08:35 PM: 025aae25 INFO   Processing form wai-course-list/submission 08bb4060-e806-11ec-a964-b797b2be781f
Jun 9, 04:08:35 PM: 025aae25 Duration: 157.85 ms	Memory Usage: 59 MB	Init Duration: 192.22 ms	
Jun 9, 04:17:04 PM: 46231f6f INFO   Processing form wai-course-list/submission 3839a600-e807-11ec-b778-15b22f086f07
Jun 9, 04:17:04 PM: 46231f6f Duration: 157.42 ms	Memory Usage: 59 MB	Init Duration: 159.48 ms	
Jun 9, 04:25:06 PM: 75c7b01a INFO   Processing form wai-course-list/submission 57b45060-e808-11ec-9a22-311e9b530b82
Jun 9, 04:25:07 PM: 75c7b01a Duration: 228.34 ms	Memory Usage: 59 MB	Init Duration: 183.94 ms	
Jun 9, 05:24:03 PM: 66d374e3 INFO   Processing form wai-course-list/submission 93860f40-e810-11ec-931e-c9ddb9e20f86
Jun 9, 05:24:03 PM: 66d374e3 ERROR  GitHub returned failure: 422, {"message":"Invalid request.\n\nFor 'links/0/schema', \"submission_date\" is not an object.","documentation_url":"https://docs.github.com/rest/reference/repos#create-a-repository-dispatch-event"}
Jun 9, 05:24:03 PM: 66d374e3 Duration: 138.49 ms	Memory Usage: 59 MB	Init Duration: 153.33 ms	
Jun 9, 05:58:13 PM: ea4a425d INFO   Processing form wai-course-list/submission 59b4a150-e815-11ec-8d0a-eb1c364e5b7b
```

Looks like submission_date conversion to JSON is broken.

Thinking the error message should include the submission ID and more if can easily pass data in a redirect.

**Comment by SteveALee** [comment] 2022-06-16 14:20
@shawna-slh  - I think I entered all the data the same except Description and C0mments and it [worked](https://github.com/w3c/wai-course-list/pull/198/files).

So either the bug was due to content in those fields (or size) or there was another issue.

**Comment by SteveALee** [comment] 2022-06-16 14:46
Guessing the preview dates being out is due to date handling functions mixing UTC and local times zones. Tricky stuff.

**Comment by SteveALee** [comment] 2022-06-16 16:01
For now we'll keep an eye on this as currently is not reproducible. If a problem occurs then if this issues is updated I'll get notified and look into it ASAP.

**Comment by leticiaseixas** [comment] 2022-07-22 15:40
After running some tests I identified that the error is actually caused by copying some special characters that are not transposed in JSON in the correct way - in particular the bullet points under "[Course content (syllabus)](https://www.w3.org/WAI/fundamentals/foundations-course/#what-you-get-from-the-course)". It is worth taking a closer look at this.

**Comment by SteveALee** [comment] 2022-07-22 16:22
Great spot. I had thought I'd tested correct escaping.

Is it possible to give example data entry that breaks?

**Comment by SteveALee** [comment] 2022-07-22 16:23
Oh, sorry, just spotted linknto video

**Comment by SteveALee** [comment] 2022-08-05 14:03
@leticiaseixas I can't repo it

I tried adding the 5 curricula topics only and in debug mode we get valid JSON. I copied the text (not bullets) which is what @shawna-slh appears to have done in the video.

so

- is it definitely those that cause the error?
- if so, what browser? I wonder if Firefox (which I use) is tidying up the copied text
- if not - what can it be? :(

**Comment by SteveALee** [comment] 2022-08-05 14:13
Ahah, So when I pass the JSON on to Github it goes boom!

```
Aug 5, 03:09:05 PM: 1adb56da ERROR  GitHub returned failure: 422, {"message":"Invalid request.\n\n\"form\" is not a permitted key.\n\"event_type\" wasn't supplied.","documentation_url":"https://docs.github.com/rest/reference/repos#create-a-repository-dispatch-event"}
```

So despite it being valid JSON (I validated it) GitHub exploads. I'll have to debug the action next

**Comment by SteveALee** [comment] 2022-08-05 17:42
Problem turn out to be when sending to github the JSON is NOT utf-8 encoded by default so unicode chars got mangled break the JSON - D'oh!

Content-type header needs to be "application/json;charset=UTF-8"

Fixed

@shawna-slh this is fixed in live site as the wai-website Netlify function has been updated.

**Closed by SteveALee** 2022-08-05 17:42 UTC
Labels: bug
